DienThoaiDiDong/Controllers/KhachhangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyClass.DAO;
using MyClass.Models;

namespace DienThoaiDiDong.Controllers
{
    public class KhachhangController : Controller
    {
        UserDAO userDAO = new UserDAO();
        // GET: Khachhang
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection filed)
        {
            String username = filed["username"];
            String password = XString.ToMD5(filed["password"]);
            //
            User row_user = userDAO.getRow(username, "Customer");
            String strError = "";
            if (row_user == null)
            {
                strError = " Tên đăng nhập không tồn tại";
            }
            else
            {
                if (password.Equals(row_user.Password))
                {
                    Session["UserCustomer"] = username;
                    Session["CustomerId"] = row_user.Id;
                    return Redirect("~/");
                }
                else
                {
                    strError = password;
                }
            }
            ViewBag.Error = "<span class='text-danger'>" + strError + "</div>";
            return View();
        }
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(FormCollection form, User user)
        {
            if (ModelState.IsValid)
            {
                string username = form["username"];
                string password = XString.ToMD5(form["password"]);

                user.Username = username;
                user.Password = password;
                user.Roles = "Customer";
                user.Gender = 1;
                user.CreatedBy = Convert.ToInt32(Session["UserId"].ToString());
                user.CreatedAt = DateTime.Now;
                user.Status = 1;

                userDAO.Insert(user);
                return Redirect("/");
            }
            return View(user);
        }
        public ActionResult DangXuat()
        {
            Session["UserCustomer"] = "";
            Session["CustomerId"] = "";
            return Redirect("/");

        }

    }
}

DienThoaiDiDong/Views/Khachhang/DangKy.cshtml
@model MyClass.Models.User
@{
    ViewBag.Title = "Đăng Ký";
    Layout = "~/Views/Share/_LayoutSite.cshtml";
}
@using (Html.BeginForm("DangKy", "Khachhang", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <section class="maincontent clearfix py-3">

        <div class="row">
            <div class="col-md-6 text-center py-md-5">
                <img style="width:75%" src="~/Public/images/Product/iP13-Pro-Max.png" class="img-fluid card-img-top pt-2" />

            </div>
            <div class="col-md-6 ">
                <form action="">
                    <div class="containerr">
                        <h1 style="width:70%">Đăng Ký</h1>
                        <p style="width:80%" class="text-center">Hãy nhập biểu mẫu bên dưới để đăng ký.</p>
                        <hr>
                        <label style="width:80%" for="Name"><b>Họ tên</b></label>
                        <input style="width:80%" type="text" placeholder="Nhập họ tên..." name="Fullname" required>

                        <label style="width:80%" for="Usernam"><b>Tên tài khoản</b></label>
                        <input style="width:80%" type="text" placeholder="Nhập tên tài khoản..." name="username" required>

                        <label style="width:80%" for="email"><b>Email</b></label>
                        <input style="width:80%" type="text" placeholder="Nhập Email..." name="Email" required>

                        <label style="width:80%" for="phone"><b>Số điện thoại</b></label>
                        <input style="width:80%" type="text" placeholder="Nhập số điện thoại..." name="Phone" required>

                        <label style="width:80%" for="addres"><b>Địa chỉ</b></label>
                        <input style="width:80%" type="text" placeholder="Nhập địa chỉ..." name="Address" required>

                        <label style="width:80%" for="psw"><b>Mật Khẩu</b></label>
                        <input style="width:80%" type="password" placeholder="Nhập Mật Khẩu..." name="password" required>

                        <div class="clearfix">
                            <button style="width:80%" type="submit" class="signupbtn" value="">Đăng ký</button>
                        </div>
                    </div>
                </form>
                <div class="form-group my-3">
                    @*@Html.Action("DangNhap", "Khachhang")*@
                    <span>
                        chuyển sang<a href="@Url.Action("DangNhap", "KhachHang")" class=" text-decoration-none ">  Đăng nhập</a>
                    </span>
                </div>
            </div>
        </div>
    </section>
}

DienThoaiDiDong/Views/Khachhang/DangNhap.cshtml
@{
    ViewBag.Title = "Đăng Nhập";
    Layout = "~/Views/Share/_LayoutSite.cshtml";
}

@using (Html.BeginForm("DangNhap", "Khachhang", FormMethod.Post))
{
    <section class="maincontent clearfix py-md-3">
        <div class="row">
            <div class="col-md-6 text-center py-md-3">
                <img style="width:75%" src="~/Public/images/Product/iP13-Pro-Max.png" class="img-fluid card-img-top pt-2" />
            </div>
            <div class="col-md-6">
                <form action="">
                    <div class="containerr">
                        <h1>Đăng Nhập</h1>
                        <hr>

                        <label style="width:90%" for="email"><b>Tên tài khoản</b></label>
                        <input style="width:90%" type="text" placeholder="Nhập tài khoản" name="username" required>

                        <label style="width:90%" for="psw"><b>Mật Khẩu</b></label>
                        <input style="width:90%" type="password" placeholder="Nhập Mật Khẩu" name="password" required>

                        <label style="width:90%" >
                            <input style=" margin-bottom: 15px" type="checkbox" checked="checked" name="remember"> Nhớ Đăng Nhập
                        </label>

                        <div class="clearfix  ">
                            <button style="width:90%" type="submit" class="signupbtn">Đăng Nhập</button>
                        </div>
                        <label class="text-center">
                            <a class="nav-link text-center" href="~/dang-ky"> Bạn chưa có tài khoản. Bấm vào đây để đăng ký</a>
                        </label>
                    </div>
                </form>
            </div>
        </div>
    </section>

    @*<section class="maincontent clearfix py-md-3">
        <div class="row">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
                <h2 class="text-center">Đăng Nhập</h2>
                <div class="container my-3">
                    <div class="form-group my-2">
                        <label>Tên đăng nhập</label>
                        <input name="username" type="text" class="form-control" />
                    </div>
                    <div class="form-group my-2">
                        <label>Mật khẩu</label>
                        <input  name="password" type="password" class="form-control" />
                    </div>
                    <div class="form-group my-3 text-center">
                        <button type="submit" class="btn btn-outline-success">Đăng nhập</button>
                    </div>
                    <div class="form-group my-3">
                        @Html.Raw(ViewBag.Error)
                    </div>
                </div>
            </div>
        </div>*@
    @*</section>*@
}