DienThoaiDiDong/Areas/Admin/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyClass.Models;
using MyClass.DAO;


namespace DienThoaiDiDong.Areas.Admin.Controllers
{
    public class LinkController : BaseController
    {
        LinkDAO linkDAO = new LinkDAO();

        // GET: Admin/Link
        public ActionResult Index()
        {
            return View(linkDAO.getList());
        }

        // GET: Admin/Link/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = linkDAO.getRow(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // GET: Admin/Link/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Link/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Link link)
        {
            if (ModelState.IsValid)
            {
                linkDAO.Insert(link);
                TempData["message"] = new XMessage("success", "Lưu thành công");
                return RedirectToAction("Index");
            }

            return View(link);
        }

        // GET: Admin/Link/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = linkDAO.getRow(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // POST: Admin/Link/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Slug,TypeLink,TableId")] Link link)
        {
            if (ModelState.IsValid)
            {
                linkDAO.Update(link);
                TempData["message"] = new XMessage("success", "Chỉnh sửa thành công");
                return RedirectToAction("Index");
            }
            return View(link);
        }

        // GET: Admin/Link/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = linkDAO.getRow(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // POST: Admin/Link/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Link link = linkDAO.getRow(id);
            TempData["message"] = new XMessage("success", "Xóa thành công");
            return RedirectToAction("Index");
        }

    }
}

DienThoaiDiDong/Areas/Admin/Views/Link/Create.cshtml
@model MyClass.Models.Link

@{
    ViewBag.Title = "Tạo Liên Kết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content my-2">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger text-uppercase">Tạo Liên Kết</strong>

                        </div>
                        <div class="col-md-6 text-right">
                            <button class="btn btn-sm btn-danger" type="submit" name="Create"><i class="fas fa-save"></i> Lưu[Thêm]</button>
                            <a class="btn btn-sm btn-success" href="@Url.Action("Index", "Link")"><i class="fas fa-undo-alt"></i> Quay lại</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Liên Kết<span class="text-danger">(*)</span></label>
                        @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
                    
                    </div>

                    <div class="form-group">
                        <label>Nhập liên kết<span class="text-danger">(*)</span></label>
                            @Html.EditorFor(model => model.TypeLink, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TypeLink, "", new { @class = "text-danger" })
                        
                    </div>

                    <div class="form-group">
                        <label>Bảng ID<span class="text-danger">(*)</span></label>
                            @Html.EditorFor(model => model.TableId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TableId, "", new { @class = "text-danger" })
                       
                    </div>

                    


                </div>

            </div>
        </section>
        <!-- /.content -->
    </div>
    
}

DienThoaiDiDong/Areas/Admin/Views/Link/Delete.cshtml
@model MyClass.Models.Link

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content my-2">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger text-uppercase">Xóa Liên kết</strong>

                        </div>
                        <div class="col-md-6 text-right">
                            <button class="btn btn-sm btn-danger" type="submit" value="Delete"><i class="fas fa-trash"></i> Xóa</button>
                            <a class="btn btn-sm btn-success" href="@Url.Action("Index", "Link")"><i class="fas fa-undo-alt"></i> Quay lại</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <h3>Bạn có chắc muốn xóa liên kết hay không?</h3>
                    <div class="card-body my-3">
                        <table class="table table-bordered">
                            <tr>
                                <th style="width:150px">Tiêu Đề</th>
                                <th> Nội dung</th>
                            </tr>
                            <tr>
                                <th> Liên Kết</th>
                                <th> @Html.DisplayFor(model => model.Slug)</th>
                            </tr>
                            <tr>
                                <th>Nhập Liên Kết</th>
                                <th> @Html.DisplayFor(model => model.TypeLink)</th>
                            </tr>
                            <tr>
                                <th> ID bảng</th>
                                <th> @Html.DisplayFor(model => model.TableId)</th>
                            </tr>
                        </table>


                    </div>

            </div>
        </section>
        <!-- /.content -->
    </div>
}

DienThoaiDiDong/Areas/Admin/Views/Link/Details.cshtml
@model MyClass.Models.Link

@{
    ViewBag.Title = "Thông tin chi tiết";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content my-2">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <strong class="text-danger text-uppercase">Thông tin chi tiết</strong>

                    </div>
                    <div class="col-md-6 text-right">

                        <a class="btn btn-sm btn-info" href="@Url.Action("Edit", "Link", new { id=Model.Id })"><i class="fas fa-edit"></i>Chỉnh sửa</a>
                        <a class="btn btn-sm btn-success" href="@Url.Action("Index", "Link")"><i class="fas fa-undo-alt"></i> Quay lại</a>
                    </div>
                </div>
            </div>
            <div class="card-body my-3">
                <table class="table table-bordered">
                    <tr>
                        <th style="width:150px">Tiêu Đề</th>
                        <th> Nội dung</th>
                    </tr>
                    <tr>
                        <th> Liên Kết</th>
                        <th> @Html.DisplayFor(model => model.Slug)</th>
                    </tr>
                    <tr>
                        <th>Nhập Liên Kết</th>
                        <th> @Html.DisplayFor(model => model.TypeLink)</th>
                    </tr>
                    <tr>    
                        <th> ID bảng</th>
                        <th> @Html.DisplayFor(model => model.TableId)</th>
                    </tr>
                </table>

            </div>

        </div>
    </section>
    <!-- /.content -->
</div>

DienThoaiDiDong/Areas/Admin/Views/Link/Edit.cshtml
@model MyClass.Models.Link

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- Main content -->
        <section class="content my-2">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <strong class="text-danger text-uppercase">Chỉnh sửa </strong>

                        </div>
                        <div class="col-md-6 text-right">

                            <button class="btn btn-sm btn-danger" type="submit" name="edit"><i class="fas fa-save"></i> Lưu[Cập nhật]</button>
                            <a class="btn btn-sm btn-success" href="@Url.Action("Index", "Link")"><i class="fas fa-undo-alt"></i> Quay lại</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Liên Kết<span class="text-danger">(*)</span></label>
                        @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        <label>Nhập liên kết<span class="text-danger">(*)</span></label>
                        @Html.EditorFor(model => model.TypeLink, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TypeLink, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        <label>Bảng ID<span class="text-danger">(*)</span></label>
                        @Html.EditorFor(model => model.TableId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TableId, "", new { @class = "text-danger" })

                    </div>

                </div>

            </div>
        </section>
        <!-- /.content -->
    </div>
}

DienThoaiDiDong/Areas/Admin/Views/Link/Index.cshtml
@model IEnumerable<MyClass.Models.Link>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
}
@section header{
    <link href="~/Public/css/jquery.dataTables.min.css" rel="stylesheet" />

}

@section footer{
    <script src="~/Public/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content my-2">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <strong class="text-danger text-uppercase">Địa chỉ liên Kết</strong>

                    </div>
                    <div class="col-md-6 text-right">
                    </div>
                </div>
            </div>
            <div class="card-body">
                @Html.Partial("Message")
                <table class="table table-bordered table-striped" >
                    <thead>
                        <tr>
                            <th class="text-center" style="width:20px;">#</th>

                            <th class="text-center">
                                @Html.DisplayNameFor(model => model.Slug)
                            </th>
                            <th class="text-center">
                                Nhập liên kết
                            </th>
                            <th class="text-center">
                                Table Id
                            </th>
                         
                            <th class="text-center" style="width:20px;">ID</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-center"> <input type="checkbox" name="checkId" value=" " /> </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Slug)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.TypeLink)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.TableId)
                                </td>
                               
                                
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


            </div>

        </div>
    </section>
    <!-- /.content -->
</div>