DienThoaiDiDong/Controllers/GiohangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyClass.DAO;
using MyClass.Models;

namespace DienThoaiDiDong.Controllers
{
    public class GiohangController : Controller
    {
        ProductDAO productDAO = new ProductDAO();
        UserDAO userDAO = new UserDAO();
        OrderDAO orrderDAO = new OrderDAO();
        OrderdetailDAO orrderdetailDAO = new OrderdetailDAO();
        XCart xcart = new XCart();
        // GET: Giohang
        public ActionResult Index()
        {
            List<CartItem> listcart = xcart.getCart();
            return View("Index",listcart);
        }
        public ActionResult CartAdd(int productid)
        {
            Product product = productDAO.getRow(productid);
            CartItem cartitem = new CartItem(product.Id, product.Name, product.Img, product.Price, 1);
            //add vào giỏ hàng
            List<CartItem> listcart = xcart.AddCart(cartitem, productid);
            return RedirectToAction("Index","Giohang");
        }
        public ActionResult CartDel(int productid)
        {
            xcart.DelCart(productid);
            return RedirectToAction("Index", "Giohang");
        }
        //CartUpdate
        public ActionResult CartUpdate(FormCollection form)
        {
            if (!string.IsNullOrEmpty(form["CAPNHAT"]))
            {
                var listqty = form["qty"];
                var listarr = listqty.Split(',');
                xcart.UpdateCart(listarr);

            }
            return RedirectToAction("Index", "Giohang");
        }
        //CartDelAll
        public ActionResult CartDelAll()
        {
            xcart.DelCart();
            return RedirectToAction("Index", "Giohang");
        }
        //thanhtoasn
        public ActionResult ThanhToan()
        {
            List <CartItem> listcart = xcart.getCart();
            //kiểm tra trang thái đăng nhập người dùng ==> khách hàng
            if (Session["UserCustomer"].Equals(""))
            {
                return Redirect("~/dang-nhap");//Chuyển hướng URL đến đăng nhập 
            }
            int userid = int.Parse(Session["CustomerId"].ToString());
            User user = userDAO.getRow(userid);
            ViewBag.user = user;
            return View("ThanhToan",listcart);
        }
        //DatMua
        public ActionResult DatMua(FormCollection filed)
        {
            //Lưu thông tin vào CSDL Order và OrderDetail
            int userid = int.Parse(Session["CustomerId"].ToString());
            User user = userDAO.getRow(userid);

            String note = filed["Note"];
            String name = filed["ReceiverName"];
            String email = filed["ReceiverEmail"];
            String phone = filed["ReceiverPhone"];
            String addres = filed["ReceiverAddress"];
            //Tạo đối tượng dươn hàng
            Order order = new Order();
            order.UserId = userid;
            order.Note = note;
            order.ReceiverName = name;
            order.ReceiverEmail = email;
            order.ReceiverPhone = phone;
            order.ReceiverAdress = addres;
            order.CreatedAt = DateTime.Now;
            order.CreatedBy = Convert.ToInt32(Session["UserId"].ToString());
            order.Status = 1;
            if(orrderDAO.Insert(order)==1)
            {
                //Thêm vào chi toeets đơn hàng
                List<CartItem> listcart = xcart.getCart();
                foreach(CartItem cartItem in listcart)
                {
                    OrderDetail orderdetail = new OrderDetail();
                    orderdetail.Orderid = order.Id;
                    orderdetail.Productid = cartItem.ProductId;
                    orderdetail.Price = cartItem.Price;
                    orderdetail.Quantity = cartItem.Qty;
                    orderdetail.Amount = cartItem.Amount;
                    orrderdetailDAO.Insert(orderdetail);
                }    
            }    

            return Redirect("~/thanh-cong");//Chuyển hướng URL đến đăng nhập 
           
        }
        public ActionResult ThanhCong()
        {
            List<CartItem> listcart = xcart.getCart();
            return View("ThanhCong", listcart);
        }
    }
}

DienThoaiDiDong/Controllers/SiteController.cs
using MyClass.DAO;
using MyClass.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace DienThoaiDiDong.Controllers
{
    public class SiteController : Controller
    {
        private LinkDAO linkDAO = new LinkDAO();
        private ProductDAO productDAO = new ProductDAO();
        private PostDAO postDAO = new PostDAO();
        private CategoryDAO categoryDAO = new CategoryDAO();
        private TopicDAO topicDAO = new TopicDAO();
        private SupplierDAO supplierDAO = new SupplierDAO();
        // GET: Site
        public ActionResult Index(string slug = null, int? page = null)
        {
            if (slug == null)
            {
                return this.Home();//Trang chủ
            }
            else
            {
                Link link = linkDAO.getRow(slug);
                if (link != null)
                { // link khác rỗng thì kiểm tra slug
                    string typelink = link.TypeLink;
                    switch (typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug, page);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug);
                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }
                        case "supplier":
                            {
                                return this.PostSupplier(slug);
                            }
                        default:
                            {
                                return this.Error404(slug);
                            }
                    }
                }
                else
                {
                    Product product = productDAO.getRow(slug);
                    if (product != null)
                    {
                        return this.ProductDetail(product);
                    }
                    else
                    {
                        Post post = postDAO.getRow(slug, "Post");
                        if (post != null)
                        {
                            return this.PostDetail(post);
                        }
                        else
                        {
                            return this.Error404(slug);
                        }
                    }
                }
            }
        }
        public ActionResult Home()
        {
            List<ProductInfo> productNew = productDAO.getList(8);
            ViewBag.ProductNew = productNew;
            List<Category> list = categoryDAO.getListByParentId(0);
            return View("Home", list);
        }
        public ActionResult HomeProduct(int id)
        {
            Category category = categoryDAO.getRow(id);
            ViewBag.Category = category;
            // xử lý danh mục loại sản phẩm 3 cấp

            /* Tạo 1 dánh sách để lấy tất cả các id của các danh mục có chứa cấp con ( parentid khác 0) */
            List<int> listcatid = new List<int>();
            listcatid.Add(id); // nhập cấp đầu tiên

            /*  tạo danh sách quét các cấp con của cấp 1 (cấp đầu tiên) */
            List<Category> listcategory2 = categoryDAO.getListByParentId(id);

            /* kiểm tra xem trong cấp 1 có cấp con hay không // nếu có chạy vòng lặp để quét rồi thêm vào cấp cha */
            if (listcategory2.Count() != 0)
            {
                foreach (var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);    /* thêm vào cấp cha (cấp cao nhất) */
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);

                    /* kiểm tra xem trong cấp 2 có cấp con hay không // nếu có chạy vòng lặp để quét rồi thêm vào cấp cha */
                    if (listcategory3.Count() != 0)
                    {
                        foreach (var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);    /* thêm vào cấp cha (cấp cao nhất) */
                        }
                    }
                }
            }
            List<ProductInfo> list = productDAO.getListByListCatId(listcatid, 4);
            return View("HomeProduct", list);
        }
        public ActionResult ProductCategory(string slug, int? page)
        {

            int pageNumber = page ?? 1; //trang hiện tại 
            int pageSize = 8;
            Category category = categoryDAO.getRow(slug);
            // lấy category dựa vào slug
            ViewBag.Category = category;
            List<int> listcatid = new List<int>();
            listcatid.Add(category.Id);
            List<Category> listcategory2 = categoryDAO.getListByParentId(category.Id);
            if (listcategory2.Count() != 0)
            {
                foreach (var category2 in listcategory2)
                {
                    listcatid.Add(category2.Id);
                    List<Category> listcategory3 = categoryDAO.getListByParentId(category2.Id);

                    if (listcategory3.Count() != 0)
                    {
                        foreach (var category3 in listcategory3)
                        {
                            listcatid.Add(category3.Id);
                        }
                    }
                }
            }
            // đưa số lượng mẫy tin cần lấy
            IPagedList<ProductInfo> list = productDAO.getListByListCatId(listcatid, pageSize, pageNumber);
            return View("ProductCategory", list);
        }
        public ActionResult ProductDetail(Product product)
        {
            //ViewBag.Supplier = supplierDAO.getRow(product.SupplierId);

            return View("ProductDetail", product);
        }
        public ActionResult PostTopic(string slug)
        {
            Topic topic = topicDAO.getRow(slug);
            ViewBag.Topic = topic;
            List<PostInfo> list = postDAO.getListByTopicId(topic.Id, "Post", null);
            return View("PostTopic", list);
        }
        public ActionResult PostPage(string slug)
        {
            Post post = postDAO.getRow(slug, "Page");
            return View("PostPage", post);
        }
        public ActionResult PostDetail(Post post)
        {
            ViewBag.ListOrther = postDAO.getListByTopicId(post.Topid, "Post", post.Id);
            //bài viết liên quan
            return View("PostDetail", post);
        }
        public ActionResult PostSupplier(string slug)
        {
            return View("PostSupplier");
        }
        public ActionResult Error404(string slug)
        {
            return View("Error404");
        }

        public ActionResult Product(int? page)
        {
            int pageNumber = page ?? 1; //trang hiện tại 
            int pageSize = 8;

            IPagedList<ProductInfo> list = productDAO.getList(pageSize, pageNumber);
            return View("Product", list);
        }
        public ActionResult Post(/*int? page*/)
        {
            //int pageNumber = page ?? 1; //trang hiện tại 
            //int pageSize = 6;
            List<PostInfo> list = postDAO.getList("Post"/*, pageSize, pageNumber*/);
            return View("Post", list);
        }
        public ActionResult HomePost(/*int? page*/)
        {
            //int pageNumber = page ?? 1; //trang hiện tại 
            //int pageSize = 4;
            List<PostInfo> list = postDAO.getListByPost("Post"/*, pageSize, pageNumber*/);
            return View("HomePost", list);
        }

    }
}

DienThoaiDiDong/Views/Giohang/Index.cshtml
@model IEnumerable<CartItem>
@{
    ViewBag.Title = "Giỏ Hàng";
    Layout = "~/Views/Share/_LayoutSite.cshtml";


}
<section class="main-container clearfix">
    <div class="container my-3">
        <div class="row">
            <div class="category-title position-relative py-2">
                <h2 class="text-center text-uppercase text-success">Giỏ Hàng</h2>
            </div>
            @if (Model != null)
            {
                using (Html.BeginForm("CartUpdate", "Giohang", FormMethod.Post))
                {
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width:70px;" class="text-center">Mã SP</th>
                                <th style="width:100px;" class="text-center">Hình</th>
                                <th class="text-center">Tên sản Phẩm</th>
                                <th class="text-center">Giá</th>
                                <th style="width:100px;" class="text-center">Số lượng </th>
                                <th class="text-center">Thành tiền</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ decimal tongtien = 0;}
                            @foreach (var cart in Model)
                            {
                                <tr>
                                    <td class="text-center">@cart.ProductId</td>
                                    <td class="text-center"><img class="img-fluid card-img-top" src="~/Public/images/Product/@cart.Img" alt="@cart.Name" /></td>
                                    <td class="text-center">@cart.Name</td>
                                    <td class="text-center"> @string.Format("{0:0,0}", cart.Price) VNĐ</td>
                                    <td class="text-center"><input name="qty" value="@cart.Qty" type="number" min="1" /></td>
                                    <td class="text-center">@string.Format("{0:0,0}", cart.Amount) VNĐ</td>
                                    <td class="text-center">
                                        <a class="text-danger" href="@Url.Action("CartDel", "Giohang", new { productid = cart.ProductId }) "><i class="far fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                                tongtien += cart.Amount;
                            }
                            <tr>
                                <td colspan="4">
                                    <a href="@Url.Action("Index", "Site")" class="btn btn-sm btn-success">Mua thêm sản phẩm</a>
                                    <input class="btn btn-sm btn-info" name="CAPNHAT" value="Cập nhật" type="submit" />
                                    <a href="@Url.Action("CartDelAll", "Giohang")" class="btn btn-sm btn-danger">Xóa sản phẩm</a>
                                    <a href="@Url.Action("ThanhToan", "Giohang")" class="btn btn-sm btn-success">Thanh toán</a>
                                </td>
                                <td class="text-end "><b>Tổng tiền:</b></td>
                                <td colspan="2" class="text-center">
                                    <b>
                                        @string.Format("{0:0,0}", tongtien) VNĐ
                                    </b>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }
            }
            else
            {
                <h4 class="text-center text-danger text-uppercase">Không có sản phẩm nào trong giỏ hàng.</h4>
                <div class="row">
                    <a href="@Url.Action("Index", "Site")" class="btn btn-sm btn-primary text-center">Mua thêm sản phẩm</a>
                </div>
            }
        </div>
    </div>
</section>

DienThoaiDiDong/Views/Giohang/ThanhCong.cshtml
@model IEnumerable<CartItem>
@{
    ViewBag.Title = "Đơn hàng đặt thành công";
    Layout = "~/Views/Share/_LayoutSite.cshtml";
}
@{
    var user = ViewBag.user;
}
<div class="row">
    <div class="col-md-12 text-center">
        <h4 class="text-center text-danger py-3">Đơn hàng đặt thành công !</h4>
        <div class="container my-3">
            <div class="row">
                <div class="category-title position-relative py-2">
                    <h2 class="text-center text-uppercase text-success">Đơn hàng của bạn</h2>
                </div>
                @foreach (var cart in Model)
                {
                    <div class="col-md-4">
                        <img style="width:75%;" class="img-fluid card-img-top" src="~/Public/images/Product/@cart.Img" alt="@cart.Name" />
                    </div>
                }
            <div class="col-md-6 py-4">
                <table class="table table-bordered">
                    @{ decimal tongtien = 0;}
                    @foreach (var cart in Model)
                    {
                        <tr>
                            <th style="width:200px;"class="table-info">Tiêu Đề</th>
                            <th class="table-info"> Nội dung</th>
                        </tr>
                        <tr>
                            <th>Tên sản Phẩm</th>
                            <th>@cart.Name</th>
                        </tr>
                        <tr>
                            <th>Giá</th>
                            <th> @string.Format("{0:0,0}", cart.Price) VNĐ</th>
                        </tr>
                        <tr>
                            <th>Số lượng</th>
                            <th>@cart.Qty</th>
                        </tr>
                        <tr>
                            <th>Thành tiền</th>
                            <th>@string.Format("{0:0,0}", cart.Amount) VNĐ</th>
                        </tr>
                        tongtien += cart.Amount;
                    }
                    </table>


               
            </div>
            </div>
        </div>
        <div class="col-md-12 py-3">
            <a class="btn btn-sm btn-success text-center" href="@Url.Action("Index")"><i class="fas fa-undo-alt"></i> Quay lại giỏ hàng</a>
            <a href="@Url.Action("Index", "Site")" class="btn btn-sm btn-success">Quay lại trang chủ</a>
        </div>

    </div>
</div>

DienThoaiDiDong/Views/Giohang/ThanhToan.cshtml
@model IEnumerable<CartItem>
@{
    ViewBag.Title = "Thanh Toán";
    Layout = "~/Views/Share/_LayoutSite.cshtml";
}
@{
    var user = ViewBag.user;
}
@using (Html.BeginForm("DatMua", "Giohang", FormMethod.Post))
{
<section class="main-container clearfix">
    <div class="container my-3">
        <div class="row">
            <div class="category-title position-relative py-2">
                <h2 class="text-center text-uppercase text-success">Thanh Toán</h2>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width:70px;" class="text-center">Mã SP</th>
                                <th style="width:100px;" class="text-center">Hình</th>
                                <th class="text-center">Tên sản Phẩm</th>
                                <th class="text-center">Giá</th>
                                <th style="width:100px;" class="text-center">Số lượng </th>
                                <th class="text-center">Thành tiền</th>
                                <th class="text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ decimal tongtien = 0;}
                            @foreach (var cart in Model)
                            {
                                <tr>
                                    <td class="text-center">@cart.ProductId</td>
                                    <td class="text-center"><img class="img-fluid card-img-top" src="~/Public/images/Product/@cart.Img" alt="@cart.Name" /></td>
                                    <td class="text-center">@cart.Name</td>
                                    <td class="text-center"> @string.Format("{0:0,0}", cart.Price) VNĐ</td>
                                    <td class="text-center">@cart.Qty</td>
                                    <td class="text-center">@string.Format("{0:0,0}", cart.Amount) VNĐ</td>
                                    <td class="text-center">
                                        <a class="text-danger" href="@Url.Action("CartDel", "Giohang", new { productid = cart.ProductId }) "><i class="far fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                                tongtien += cart.Amount;
                            }
                        </tbody>
                    </table>

                    <h2 class="text-center">THÔNG TIN KHÁCH HÀNG</h2>
                    <div class="form-control my-2">
                        <label>Họ tên khách hàng </label>
                        <input name="Fullname" readonly value="@user.Fullname" class="form-control" />
                    </div>
                    <div class="form-control my-2">
                        <label>Email </label>
                        <input name="Email" readonly value="@user.Email" class="form-control" />
                    </div>
                    <div class="form-control my-2">
                        <label>Điện thoại </label>
                        <input name="Phone" readonly value="@user.Phone" class="form-control" />
                    </div>
                    <div class="form-control my-2">
                        <label>Điạ chỉ</label>
                        <input name="Address" readonly value="@user.Address" class="form-control" />
                    </div>
                    <h2 class="text-center">THÔNG TIN NGƯỜI NHẬN</h2>
                    <div class="form-control my-2">
                        <label>Họ tên người nhận </label>
                        <input name="ReceiverName" class="form-control" />
                    </div>  
                    <div class="form-control my-2">
                        <label>Email </label>
                        <input name="ReceiverEmail" class="form-control" />
                    </div>
                    <div class="form-control my-2">
                        <label>Điện thoại </label>
                        <input name="ReceiverPhone" class="form-control" />
                    </div>
                    <div class="form-control my-2">
                        <label>Điạ chỉ</label>
                        <input name="ReceiverAddress" class="form-control" />
                    </div>
                    <div class="form-control my-2">
                        <label>Ghi chú</label>
                        <textarea name="Note" class="form-control" rows="2"></textarea>
                    </div>
                </div>
                <div class="col-md-3">
                    <h3>Thông tin:</h3>
                    <p>Tổng tiền: <b>@string.Format("{0:0,0}", tongtien) VNĐ</b></p>
                    <p>Tiền giảm:  VNĐ</p>
                    <button type="submit" class="btn btn-outline-success">Đặt Mua</button>
                </div>
            </div>
        </div>
    </div>
  </section>
}